import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Album, ID, Playlist, Track } from '@/types';

interface LibraryState {
  favoriteTrackIds: string[];
  savedAlbums: Album[];
  followedArtistIds: string[];
  playlists: Playlist[];
}

const initialState: LibraryState = {
  favoriteTrackIds: [],
  savedAlbums: [],
  followedArtistIds: [],
  playlists: [],
};

const librarySlice = createSlice({
  name: 'library',
  initialState,
  reducers: {
    toggleFavoriteTrack(state, action: PayloadAction<Track | string>) {
      const id = typeof action.payload === 'string' ? action.payload : action.payload.id;
      state.favoriteTrackIds = state.favoriteTrackIds.includes(id)
        ? state.favoriteTrackIds.filter((t) => t !== id)
        : [id, ...state.favoriteTrackIds];
    },
    toggleSavedAlbum(state, action: PayloadAction<Album>) {
      const exists = state.savedAlbums.some((a) => a.id === action.payload.id);
      state.savedAlbums = exists
        ? state.savedAlbums.filter((a) => a.id !== action.payload.id)
        : [{ ...action.payload, tracks: undefined }, ...state.savedAlbums];
    },
    toggleFollowArtist(state, action: PayloadAction<string>) {
      const id = action.payload;
      state.followedArtistIds = state.followedArtistIds.includes(id)
        ? state.followedArtistIds.filter((a) => a !== id)
        : [id, ...state.followedArtistIds];
    },

    /** Create an empty playlist (newest first). Id is generated by the caller. */
    createPlaylist(state, action: PayloadAction<{ id: ID; title: string }>) {
      state.playlists.unshift({
        id: action.payload.id,
        title: action.payload.title.trim(),
        cover: '', // empty until the first track is added
        trackIds: [],
        curated: false,
      });
    },
    renamePlaylist(state, action: PayloadAction<{ id: ID; title: string }>) {
      const pl = state.playlists.find((p) => p.id === action.payload.id);
      if (pl) pl.title = action.payload.title.trim();
    },
    deletePlaylist(state, action: PayloadAction<{ id: ID }>) {
      state.playlists = state.playlists.filter((p) => p.id !== action.payload.id);
    },
    /**
     * Append a track (preserving add order). De-duped, and the playlist adopts
     * the first track's artwork as its cover while it has none.
     */
    addTrackToPlaylist(
      state,
      action: PayloadAction<{ playlistId: ID; trackId: ID; artwork?: string }>,
    ) {
      const pl = state.playlists.find((p) => p.id === action.payload.playlistId);
      if (!pl || pl.trackIds.includes(action.payload.trackId)) return;
      pl.trackIds.push(action.payload.trackId);
      if (!pl.cover && action.payload.artwork) pl.cover = action.payload.artwork;
    },
    removeTrackFromPlaylist(state, action: PayloadAction<{ playlistId: ID; trackId: ID }>) {
      const pl = state.playlists.find((p) => p.id === action.payload.playlistId);
      if (!pl) return;
      pl.trackIds = pl.trackIds.filter((id) => id !== action.payload.trackId);
      // Cover is kept as-is otherwise; reset only when the playlist empties out.
      if (pl.trackIds.length === 0) pl.cover = '';
    },
  },
});

export const {
  toggleFavoriteTrack,
  toggleSavedAlbum,
  toggleFollowArtist,
  createPlaylist,
  renamePlaylist,
  deletePlaylist,
  addTrackToPlaylist,
  removeTrackFromPlaylist,
} = librarySlice.actions;
export default librarySlice.reducer;
